### ISSUE TITLE
Property enhancements

### ISSUE THREAD

**Issue by llafuente** [bjorn/tiled#129]
Hi,

I was playing around with tiled for a few time, and I find a big pain the system that actually tiled has to define objects properties for games.
Not because it's not flexible, it's just is not intuitive for new people in a dev team. You should know and remember all the properties needed to do a Door, for example.

So my request is simple.
Either support some Game Data formats (like FGD: https://developer.valvesoftware.com/wiki/FGD) or build a new one.

I think the next part could be like a prototype to build the spec on top.

The Object form has the folowing fields:
- Name (String)
- Type (String)
- Properties (String pairs)
- X (Float)
- Y (Float)

Type should be a Choice list and also a Text box (to keep compatibility and support advanced behaviours)
Depend on the selection, Properties get filled.

Properties:
The name could be a Choice list or String
The value now have a type (default: string)
"Do not add more properties" support

Types for value:
- Object [name]
- Object [name] but with a type forced
- Object [property[,]] "link" properties from object into another
- A color picker with an formatted output for example: r,g,b,a / rgba(r,g,b,a) / #rrggbb etc...
- Choices list
- Angle
- A tile (in use to keep things easy)
- A tileset (in use to keep things easy)
- basic types: String, float, integer and TEXT (a big TEXT!!!)
- basic type combo: for example: integer integer (this could define vector)

Misc
Object to Object relationship could be displayed with a line.
Vectors should be displayed with a line centered in the object.

Format example (JSON-ish)

<pre>
Vector = {
    value:{ type: ["integer", "integer"] }, // optional at the end, but could be there
};

Switch = {
    initial: { type: "string" : default: "off"},
    target: { type: "object" : default: null, filter_by_type: false, get_property: false, get_name: true},
    delay: { type: "integer" : default: "1000", comment: "milliseconds"},
};

// suppose you have a tile animiation: 0 1 2 3 4...
TileAnimation = {
    start_tile: { type: "tile" : default: "0", comment: "Choose the first tile"},
    end_tile: { type: "tile" : default: "0", comment: "Choose the last tile"},
    fps: { type: "integer" : default: "24", comment: "Frames per second"},
    rotation: { type: "angle" : default: "0", comment: "Rotation in degree"},
};

// suppose you have a tile animiation: 0 1 2 3 4...
Prop = {
    life: { type: "integer" : default: "100"},
    on_fire: { type: "text" : default: "", comment: "This will evaled when the prop life down to cero."},
    on_die: { type: "text" : default: "", comment: "This will evaled when the prop life down to cero."},
};
</pre>

It's just a propposal...

**Comment by bjorn** [comment]
This request contains a huge amount of related features. Some of them have been implemented recently, some are still pending implementation. Here's a list of issues with overlapping scope:

- [x] Allow specifying the type of a property #14 
- [x] Dynamic placeable objects with default properties for custom engine #365 
- [x] Color as a property type #1275
- [x] Multiline properties #205 
- [ ] Connecting Objects #707
- [ ] Request to Add Support for Enumeration Properties #1211 

I think it would make sense to open additional issues for other things requested here, and then to close this issue.

**Comment by bjorn** [comment]
I've lookup up and created more issues about specific things requested here:

- [ ] Type should be a Choice list and also a Text box #823 (and related #273)
- [ ] "Do not add more properties" support #2132
- [ ] Add support for nested (dictionary-type) properties  #489
- [ ] Comments on custom property definitions #2133

I didn't create issues for the following mentioned features:

* Angle, tile and tileset property types ("angle" is covered by "number", "tileset" is covered by "file" and I'm not sure about the value of "tile")
* Explicit vector property type (can be covered by #489 or just by having separate x and y properties)
* Display vector property as line on object (I've opened #2134 about enabling custom visualizations)
* Custom format for defining custom properties (I think XML and JSON are fine)

I'll close this issue now since there would be no point in keeping it open until everything is implemented. Thanks for the great list of suggestions @llafuente! With time I hope to get around to implementing more of them. :-)
